[player.sprites]
heart_blue = "sprites/player/heart_blue.png"
heart_red = "sprites/player/heart_red.png"

[sans.sprites]
sans = "sprites/sans/sans.png"
gaster_blaster_0 = "sprites/sans/gaster_blaster_0.png"
gaster_blaster_1 = "sprites/sans/gaster_blaster_1.png"
gaster_blaster_2 = "sprites/sans/gaster_blaster_2.png"
gaster_blaster_3 = "sprites/sans/gaster_blaster_3.png"
gaster_blaster_4 = "sprites/sans/gaster_blaster_4.png"
gaster_blaster_5 = "sprites/sans/gaster_blaster_5.png"

[ui.sprites]
button_fight = "sprites/ui/button_fight.png"
button_act = "sprites/ui/button_act.png"
button_item = "sprites/ui/button_item.png"
button_mercy = "sprites/ui/button_mercy.png"
