[player.sprites]
heart_blue = "sprites/player/heart_blue.png"
heart_red = "sprites/player/heart_red.png"

[sans.sprites]
sans = "sprites/sans/sans.png"
gaster_blaster = "sprites/sans/gaster_blaster.png"
