[player.sprites]
heart_blue = "sprites/player/heart_blue.png"
heart_red = "sprites/player/heart_red.png"

[sans.sprites]
sans = "sprites/sans/sans.png"

[ui.sprites]
button_fight = "sprites/ui/button_fight.png"
button_act = "sprites/ui/button_act.png"
button_item = "sprites/ui/button_item.png"
button_mercy = "sprites/ui/button_mercy.png"
attack_meter_left = "sprites/ui/attack_meter_left.png"
attack_meter_right = "sprites/ui/attack_meter_right.png"
game_over = "sprites/ui/game_over.png"
speach_box = "sprites/ui/speach_box.png"
bones_horizontal = "sprites/attacks/bones_horizontal.png"
bones_vertical = "sprites/attacks/bones_vertical.png"

[gaster_blaster_0]
output_type = "binary"

[gaster_blaster_0.sprites.gaster_blaster_0_0]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 0

[gaster_blaster_0.sprites.gaster_blaster_0_1]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 18

[gaster_blaster_0.sprites.gaster_blaster_0_2]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 36

[gaster_blaster_0.sprites.gaster_blaster_0_3]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 54

[gaster_blaster_0.sprites.gaster_blaster_0_4]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 72

[gaster_blaster_0.sprites.gaster_blaster_0_5]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 90

[gaster_blaster_0.sprites.gaster_blaster_0_6]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 108

[gaster_blaster_0.sprites.gaster_blaster_0_7]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 126

[gaster_blaster_0.sprites.gaster_blaster_0_8]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 144

[gaster_blaster_0.sprites.gaster_blaster_0_9]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 162

[gaster_blaster_0.sprites.gaster_blaster_0_10]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 180

[gaster_blaster_0.sprites.gaster_blaster_0_11]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 198

[gaster_blaster_0.sprites.gaster_blaster_0_12]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 216

[gaster_blaster_0.sprites.gaster_blaster_0_13]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 234

[gaster_blaster_0.sprites.gaster_blaster_0_14]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 252

[gaster_blaster_0.sprites.gaster_blaster_0_15]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 270

[gaster_blaster_0.sprites.gaster_blaster_0_16]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 288

[gaster_blaster_0.sprites.gaster_blaster_0_17]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 306

[gaster_blaster_0.sprites.gaster_blaster_0_18]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 324

[gaster_blaster_0.sprites.gaster_blaster_0_19]
path = "sprites/sans/gaster_blaster_0.png"
rotation = 342

[gaster_blaster_1]
output_type = "binary"

[gaster_blaster_1.sprites.gaster_blaster_1_0]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 0

[gaster_blaster_1.sprites.gaster_blaster_1_1]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 18

[gaster_blaster_1.sprites.gaster_blaster_1_2]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 36

[gaster_blaster_1.sprites.gaster_blaster_1_3]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 54

[gaster_blaster_1.sprites.gaster_blaster_1_4]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 72

[gaster_blaster_1.sprites.gaster_blaster_1_5]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 90

[gaster_blaster_1.sprites.gaster_blaster_1_6]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 108

[gaster_blaster_1.sprites.gaster_blaster_1_7]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 126

[gaster_blaster_1.sprites.gaster_blaster_1_8]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 144

[gaster_blaster_1.sprites.gaster_blaster_1_9]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 162

[gaster_blaster_1.sprites.gaster_blaster_1_10]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 180

[gaster_blaster_1.sprites.gaster_blaster_1_11]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 198

[gaster_blaster_1.sprites.gaster_blaster_1_12]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 216

[gaster_blaster_1.sprites.gaster_blaster_1_13]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 234

[gaster_blaster_1.sprites.gaster_blaster_1_14]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 252

[gaster_blaster_1.sprites.gaster_blaster_1_15]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 270

[gaster_blaster_1.sprites.gaster_blaster_1_16]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 288

[gaster_blaster_1.sprites.gaster_blaster_1_17]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 306

[gaster_blaster_1.sprites.gaster_blaster_1_18]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 324

[gaster_blaster_1.sprites.gaster_blaster_1_19]
path = "sprites/sans/gaster_blaster_1.png"
rotation = 342

[gaster_blaster_2]
output_type = "binary"

[gaster_blaster_2.sprites.gaster_blaster_2_0]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 0

[gaster_blaster_2.sprites.gaster_blaster_2_1]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 18

[gaster_blaster_2.sprites.gaster_blaster_2_2]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 36

[gaster_blaster_2.sprites.gaster_blaster_2_3]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 54

[gaster_blaster_2.sprites.gaster_blaster_2_4]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 72

[gaster_blaster_2.sprites.gaster_blaster_2_5]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 90

[gaster_blaster_2.sprites.gaster_blaster_2_6]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 108

[gaster_blaster_2.sprites.gaster_blaster_2_7]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 126

[gaster_blaster_2.sprites.gaster_blaster_2_8]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 144

[gaster_blaster_2.sprites.gaster_blaster_2_9]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 162

[gaster_blaster_2.sprites.gaster_blaster_2_10]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 180

[gaster_blaster_2.sprites.gaster_blaster_2_11]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 198

[gaster_blaster_2.sprites.gaster_blaster_2_12]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 216

[gaster_blaster_2.sprites.gaster_blaster_2_13]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 234

[gaster_blaster_2.sprites.gaster_blaster_2_14]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 252

[gaster_blaster_2.sprites.gaster_blaster_2_15]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 270

[gaster_blaster_2.sprites.gaster_blaster_2_16]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 288

[gaster_blaster_2.sprites.gaster_blaster_2_17]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 306

[gaster_blaster_2.sprites.gaster_blaster_2_18]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 324

[gaster_blaster_2.sprites.gaster_blaster_2_19]
path = "sprites/sans/gaster_blaster_2.png"
rotation = 342

[gaster_blaster_3]
output_type = "binary"

[gaster_blaster_3.sprites.gaster_blaster_3_0]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 0

[gaster_blaster_3.sprites.gaster_blaster_3_1]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 18

[gaster_blaster_3.sprites.gaster_blaster_3_2]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 36

[gaster_blaster_3.sprites.gaster_blaster_3_3]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 54

[gaster_blaster_3.sprites.gaster_blaster_3_4]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 72

[gaster_blaster_3.sprites.gaster_blaster_3_5]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 90

[gaster_blaster_3.sprites.gaster_blaster_3_6]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 108

[gaster_blaster_3.sprites.gaster_blaster_3_7]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 126

[gaster_blaster_3.sprites.gaster_blaster_3_8]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 144

[gaster_blaster_3.sprites.gaster_blaster_3_9]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 162

[gaster_blaster_3.sprites.gaster_blaster_3_10]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 180

[gaster_blaster_3.sprites.gaster_blaster_3_11]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 198

[gaster_blaster_3.sprites.gaster_blaster_3_12]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 216

[gaster_blaster_3.sprites.gaster_blaster_3_13]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 234

[gaster_blaster_3.sprites.gaster_blaster_3_14]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 252

[gaster_blaster_3.sprites.gaster_blaster_3_15]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 270

[gaster_blaster_3.sprites.gaster_blaster_3_16]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 288

[gaster_blaster_3.sprites.gaster_blaster_3_17]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 306

[gaster_blaster_3.sprites.gaster_blaster_3_18]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 324

[gaster_blaster_3.sprites.gaster_blaster_3_19]
path = "sprites/sans/gaster_blaster_3.png"
rotation = 342

[gaster_blaster_4]
output_type = "binary"

[gaster_blaster_4.sprites.gaster_blaster_4_0]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 0

[gaster_blaster_4.sprites.gaster_blaster_4_1]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 18

[gaster_blaster_4.sprites.gaster_blaster_4_2]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 36

[gaster_blaster_4.sprites.gaster_blaster_4_3]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 54

[gaster_blaster_4.sprites.gaster_blaster_4_4]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 72

[gaster_blaster_4.sprites.gaster_blaster_4_5]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 90

[gaster_blaster_4.sprites.gaster_blaster_4_6]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 108

[gaster_blaster_4.sprites.gaster_blaster_4_7]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 126

[gaster_blaster_4.sprites.gaster_blaster_4_8]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 144

[gaster_blaster_4.sprites.gaster_blaster_4_9]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 162

[gaster_blaster_4.sprites.gaster_blaster_4_10]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 180

[gaster_blaster_4.sprites.gaster_blaster_4_11]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 198

[gaster_blaster_4.sprites.gaster_blaster_4_12]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 216

[gaster_blaster_4.sprites.gaster_blaster_4_13]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 234

[gaster_blaster_4.sprites.gaster_blaster_4_14]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 252

[gaster_blaster_4.sprites.gaster_blaster_4_15]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 270

[gaster_blaster_4.sprites.gaster_blaster_4_16]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 288

[gaster_blaster_4.sprites.gaster_blaster_4_17]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 306

[gaster_blaster_4.sprites.gaster_blaster_4_18]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 324

[gaster_blaster_4.sprites.gaster_blaster_4_19]
path = "sprites/sans/gaster_blaster_4.png"
rotation = 342

[gaster_blaster_5]
output_type = "binary"

[gaster_blaster_5.sprites.gaster_blaster_5_0]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 0

[gaster_blaster_5.sprites.gaster_blaster_5_1]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 18

[gaster_blaster_5.sprites.gaster_blaster_5_2]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 36

[gaster_blaster_5.sprites.gaster_blaster_5_3]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 54

[gaster_blaster_5.sprites.gaster_blaster_5_4]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 72

[gaster_blaster_5.sprites.gaster_blaster_5_5]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 90

[gaster_blaster_5.sprites.gaster_blaster_5_6]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 108

[gaster_blaster_5.sprites.gaster_blaster_5_7]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 126

[gaster_blaster_5.sprites.gaster_blaster_5_8]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 144

[gaster_blaster_5.sprites.gaster_blaster_5_9]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 162

[gaster_blaster_5.sprites.gaster_blaster_5_10]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 180

[gaster_blaster_5.sprites.gaster_blaster_5_11]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 198

[gaster_blaster_5.sprites.gaster_blaster_5_12]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 216

[gaster_blaster_5.sprites.gaster_blaster_5_13]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 234

[gaster_blaster_5.sprites.gaster_blaster_5_14]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 252

[gaster_blaster_5.sprites.gaster_blaster_5_15]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 270

[gaster_blaster_5.sprites.gaster_blaster_5_16]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 288

[gaster_blaster_5.sprites.gaster_blaster_5_17]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 306

[gaster_blaster_5.sprites.gaster_blaster_5_18]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 324

[gaster_blaster_5.sprites.gaster_blaster_5_19]
path = "sprites/sans/gaster_blaster_5.png"
rotation = 342

[font_comic]
color_space = "monochrome"
header = false

[font_comic.sprites]
glyph_exclamation_mark = "sprites/fonts/comic/glyph_exclamation_mark.png"
glyph_apostrophe = "sprites/fonts/comic/glyph_apostrophe.png"
glyph_comma = "sprites/fonts/comic/glyph_comma.png"
glyph_period = "sprites/fonts/comic/glyph_period.png"
glyph_question_mark = "sprites/fonts/comic/glyph_question_mark.png"
glyph_A = "sprites/fonts/comic/glyph_A.png"
glyph_B = "sprites/fonts/comic/glyph_B.png"
glyph_C = "sprites/fonts/comic/glyph_C.png"
glyph_D = "sprites/fonts/comic/glyph_D.png"
glyph_E = "sprites/fonts/comic/glyph_E.png"
glyph_F = "sprites/fonts/comic/glyph_F.png"
glyph_G = "sprites/fonts/comic/glyph_G.png"
glyph_H = "sprites/fonts/comic/glyph_H.png"
glyph_I = "sprites/fonts/comic/glyph_I.png"
glyph_J = "sprites/fonts/comic/glyph_J.png"
glyph_K = "sprites/fonts/comic/glyph_K.png"
glyph_L = "sprites/fonts/comic/glyph_L.png"
glyph_M = "sprites/fonts/comic/glyph_M.png"
glyph_N = "sprites/fonts/comic/glyph_N.png"
glyph_O = "sprites/fonts/comic/glyph_O.png"
glyph_P = "sprites/fonts/comic/glyph_P.png"
glyph_Q = "sprites/fonts/comic/glyph_Q.png"
glyph_R = "sprites/fonts/comic/glyph_R.png"
glyph_S = "sprites/fonts/comic/glyph_S.png"
glyph_T = "sprites/fonts/comic/glyph_T.png"
glyph_U = "sprites/fonts/comic/glyph_U.png"
glyph_V = "sprites/fonts/comic/glyph_V.png"
glyph_W = "sprites/fonts/comic/glyph_W.png"
glyph_X = "sprites/fonts/comic/glyph_X.png"
glyph_Y = "sprites/fonts/comic/glyph_Y.png"
glyph_Z = "sprites/fonts/comic/glyph_Z.png"
glyph_a = "sprites/fonts/comic/glyph_a.png"
glyph_b = "sprites/fonts/comic/glyph_b.png"
glyph_c = "sprites/fonts/comic/glyph_c.png"
glyph_d = "sprites/fonts/comic/glyph_d.png"
glyph_e = "sprites/fonts/comic/glyph_e.png"
glyph_f = "sprites/fonts/comic/glyph_f.png"
glyph_g = "sprites/fonts/comic/glyph_g.png"
glyph_h = "sprites/fonts/comic/glyph_h.png"
glyph_i = "sprites/fonts/comic/glyph_i.png"
glyph_j = "sprites/fonts/comic/glyph_j.png"
glyph_k = "sprites/fonts/comic/glyph_k.png"
glyph_l = "sprites/fonts/comic/glyph_l.png"
glyph_m = "sprites/fonts/comic/glyph_m.png"
glyph_n = "sprites/fonts/comic/glyph_n.png"
glyph_o = "sprites/fonts/comic/glyph_o.png"
glyph_p = "sprites/fonts/comic/glyph_p.png"
glyph_q = "sprites/fonts/comic/glyph_q.png"
glyph_r = "sprites/fonts/comic/glyph_r.png"
glyph_s = "sprites/fonts/comic/glyph_s.png"
glyph_t = "sprites/fonts/comic/glyph_t.png"
glyph_u = "sprites/fonts/comic/glyph_u.png"
glyph_v = "sprites/fonts/comic/glyph_v.png"
glyph_w = "sprites/fonts/comic/glyph_w.png"
glyph_x = "sprites/fonts/comic/glyph_x.png"
glyph_y = "sprites/fonts/comic/glyph_y.png"
glyph_z = "sprites/fonts/comic/glyph_z.png"

[font_hud]
header = false
color_space = "monochrome"

[font_hud.sprites]
glyph_space = "sprites/fonts/hud/glyph_space.png"
glyph_slash = "sprites/fonts/hud/glyph_slash.png"
glyph_0 = "sprites/fonts/hud/glyph_0.png"
glyph_1 = "sprites/fonts/hud/glyph_1.png"
glyph_2 = "sprites/fonts/hud/glyph_2.png"
glyph_3 = "sprites/fonts/hud/glyph_3.png"
glyph_4 = "sprites/fonts/hud/glyph_4.png"
glyph_5 = "sprites/fonts/hud/glyph_5.png"
glyph_6 = "sprites/fonts/hud/glyph_6.png"
glyph_7 = "sprites/fonts/hud/glyph_7.png"
glyph_8 = "sprites/fonts/hud/glyph_8.png"
glyph_9 = "sprites/fonts/hud/glyph_9.png"
glyph_A = "sprites/fonts/hud/glyph_A.png"
glyph_B = "sprites/fonts/hud/glyph_B.png"
glyph_C = "sprites/fonts/hud/glyph_C.png"
glyph_D = "sprites/fonts/hud/glyph_D.png"
glyph_E = "sprites/fonts/hud/glyph_E.png"
glyph_F = "sprites/fonts/hud/glyph_F.png"
glyph_G = "sprites/fonts/hud/glyph_G.png"
glyph_H = "sprites/fonts/hud/glyph_H.png"
glyph_I = "sprites/fonts/hud/glyph_I.png"
glyph_J = "sprites/fonts/hud/glyph_J.png"
glyph_K = "sprites/fonts/hud/glyph_K.png"
glyph_L = "sprites/fonts/hud/glyph_L.png"
glyph_M = "sprites/fonts/hud/glyph_M.png"
glyph_N = "sprites/fonts/hud/glyph_N.png"
glyph_O = "sprites/fonts/hud/glyph_O.png"
glyph_P = "sprites/fonts/hud/glyph_P.png"
glyph_Q = "sprites/fonts/hud/glyph_Q.png"
glyph_R = "sprites/fonts/hud/glyph_R.png"
glyph_S = "sprites/fonts/hud/glyph_S.png"
glyph_T = "sprites/fonts/hud/glyph_T.png"
glyph_U = "sprites/fonts/hud/glyph_U.png"
glyph_V = "sprites/fonts/hud/glyph_V.png"
glyph_W = "sprites/fonts/hud/glyph_W.png"
glyph_X = "sprites/fonts/hud/glyph_X.png"
glyph_Y = "sprites/fonts/hud/glyph_Y.png"
glyph_Z = "sprites/fonts/hud/glyph_Z.png"
